CREATE TABLE IF NOT EXISTS poller (
  id INT AUTO_INCREMENT PRIMARY KEY,
  url VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  created_date TIMESTAMP NOT NULL,
  updated_date TIMESTAMP NOT NULL,
  alive BIT NOT NULL
);